apiVersion: v1
kind: Service
metadata:
    name: node-app
    annotations:
        service.beta.kubernetes.io/do-loadbalancer-size-unit: "2"
spec:
    $patch: replace
    type: LoadBalancer
    selector:
        app: node-app
    ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 3000
