apiVersion: v1
kind: Service
metadata:
    name: node-app
    annotations:
        service.beta.kubernetes.io/do-loadbalancer-size-unit: "2"
spec:
    type: LoadBalancer
    selector:
        app: node-app
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 3000
