apiVersion: v1
kind: Service
metadata:
    name: node-app
spec:
    type: LoadBalancer
    selector:
        app: node-app
    ports:
        - name: http
          protocol: TCP
          port: 3000
          targetPort: 3000
