apiVersion: v1
kind: PersistentVolume
metadata:
    name: postgres-pv
spec:
    storageClassName: manual
    persistentVolumeReclaimPolicy: Delete
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/data/db"
